# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ritka/3semestr/laba5

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ritka/3semestr/laba5/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ritka/3semestr/laba5/build/CMakeFiles /home/ritka/3semestr/laba5/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ritka/3semestr/laba5/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named minesweeper

# Build rule for target.
minesweeper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 minesweeper
.PHONY : minesweeper

# fast build rule for target.
minesweeper/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minesweeper.dir/build.make CMakeFiles/minesweeper.dir/build
.PHONY : minesweeper/fast

Cell.o: Cell.cpp.o
.PHONY : Cell.o

# target to build an object file
Cell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minesweeper.dir/build.make CMakeFiles/minesweeper.dir/Cell.cpp.o
.PHONY : Cell.cpp.o

Cell.i: Cell.cpp.i
.PHONY : Cell.i

# target to preprocess a source file
Cell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minesweeper.dir/build.make CMakeFiles/minesweeper.dir/Cell.cpp.i
.PHONY : Cell.cpp.i

Cell.s: Cell.cpp.s
.PHONY : Cell.s

# target to generate assembly for a file
Cell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minesweeper.dir/build.make CMakeFiles/minesweeper.dir/Cell.cpp.s
.PHONY : Cell.cpp.s

GraphicalMinesweeperGame.o: GraphicalMinesweeperGame.cpp.o
.PHONY : GraphicalMinesweeperGame.o

# target to build an object file
GraphicalMinesweeperGame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minesweeper.dir/build.make CMakeFiles/minesweeper.dir/GraphicalMinesweeperGame.cpp.o
.PHONY : GraphicalMinesweeperGame.cpp.o

GraphicalMinesweeperGame.i: GraphicalMinesweeperGame.cpp.i
.PHONY : GraphicalMinesweeperGame.i

# target to preprocess a source file
GraphicalMinesweeperGame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minesweeper.dir/build.make CMakeFiles/minesweeper.dir/GraphicalMinesweeperGame.cpp.i
.PHONY : GraphicalMinesweeperGame.cpp.i

GraphicalMinesweeperGame.s: GraphicalMinesweeperGame.cpp.s
.PHONY : GraphicalMinesweeperGame.s

# target to generate assembly for a file
GraphicalMinesweeperGame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minesweeper.dir/build.make CMakeFiles/minesweeper.dir/GraphicalMinesweeperGame.cpp.s
.PHONY : GraphicalMinesweeperGame.cpp.s

MineCell.o: MineCell.cpp.o
.PHONY : MineCell.o

# target to build an object file
MineCell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minesweeper.dir/build.make CMakeFiles/minesweeper.dir/MineCell.cpp.o
.PHONY : MineCell.cpp.o

MineCell.i: MineCell.cpp.i
.PHONY : MineCell.i

# target to preprocess a source file
MineCell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minesweeper.dir/build.make CMakeFiles/minesweeper.dir/MineCell.cpp.i
.PHONY : MineCell.cpp.i

MineCell.s: MineCell.cpp.s
.PHONY : MineCell.s

# target to generate assembly for a file
MineCell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minesweeper.dir/build.make CMakeFiles/minesweeper.dir/MineCell.cpp.s
.PHONY : MineCell.cpp.s

MineField.o: MineField.cpp.o
.PHONY : MineField.o

# target to build an object file
MineField.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minesweeper.dir/build.make CMakeFiles/minesweeper.dir/MineField.cpp.o
.PHONY : MineField.cpp.o

MineField.i: MineField.cpp.i
.PHONY : MineField.i

# target to preprocess a source file
MineField.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minesweeper.dir/build.make CMakeFiles/minesweeper.dir/MineField.cpp.i
.PHONY : MineField.cpp.i

MineField.s: MineField.cpp.s
.PHONY : MineField.s

# target to generate assembly for a file
MineField.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minesweeper.dir/build.make CMakeFiles/minesweeper.dir/MineField.cpp.s
.PHONY : MineField.cpp.s

SafeCell.o: SafeCell.cpp.o
.PHONY : SafeCell.o

# target to build an object file
SafeCell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minesweeper.dir/build.make CMakeFiles/minesweeper.dir/SafeCell.cpp.o
.PHONY : SafeCell.cpp.o

SafeCell.i: SafeCell.cpp.i
.PHONY : SafeCell.i

# target to preprocess a source file
SafeCell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minesweeper.dir/build.make CMakeFiles/minesweeper.dir/SafeCell.cpp.i
.PHONY : SafeCell.cpp.i

SafeCell.s: SafeCell.cpp.s
.PHONY : SafeCell.s

# target to generate assembly for a file
SafeCell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minesweeper.dir/build.make CMakeFiles/minesweeper.dir/SafeCell.cpp.s
.PHONY : SafeCell.cpp.s

main_graphical.o: main_graphical.cpp.o
.PHONY : main_graphical.o

# target to build an object file
main_graphical.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minesweeper.dir/build.make CMakeFiles/minesweeper.dir/main_graphical.cpp.o
.PHONY : main_graphical.cpp.o

main_graphical.i: main_graphical.cpp.i
.PHONY : main_graphical.i

# target to preprocess a source file
main_graphical.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minesweeper.dir/build.make CMakeFiles/minesweeper.dir/main_graphical.cpp.i
.PHONY : main_graphical.cpp.i

main_graphical.s: main_graphical.cpp.s
.PHONY : main_graphical.s

# target to generate assembly for a file
main_graphical.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minesweeper.dir/build.make CMakeFiles/minesweeper.dir/main_graphical.cpp.s
.PHONY : main_graphical.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... minesweeper"
	@echo "... Cell.o"
	@echo "... Cell.i"
	@echo "... Cell.s"
	@echo "... GraphicalMinesweeperGame.o"
	@echo "... GraphicalMinesweeperGame.i"
	@echo "... GraphicalMinesweeperGame.s"
	@echo "... MineCell.o"
	@echo "... MineCell.i"
	@echo "... MineCell.s"
	@echo "... MineField.o"
	@echo "... MineField.i"
	@echo "... MineField.s"
	@echo "... SafeCell.o"
	@echo "... SafeCell.i"
	@echo "... SafeCell.s"
	@echo "... main_graphical.o"
	@echo "... main_graphical.i"
	@echo "... main_graphical.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

